version: '3'

services:
  postgres:
    image: postgres:13
    container_name:
      postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name:
      backend
    env_file:
      - ./.env
    restart: always
    volumes:
      - static:/code/collected_static/
      - media:/code/media/
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name:
      frontend
    volumes:
      - static:/app/build

  gateway:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name:
      gateway
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/var/html/static
      - media:/var/html/media

volumes:
  static:
    name: static
  media:
    name: media
  pg_data:
    name: pg_data